# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(774, 407)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblQuestion = QtWidgets.QLabel(self.centralwidget)
        self.lblQuestion.setGeometry(QtCore.QRect(42, 170, 711, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblQuestion.setFont(font)
        self.lblQuestion.setText("")
        self.lblQuestion.setObjectName("lblQuestion")
        self.lineAnswer = QtWidgets.QLineEdit(self.centralwidget)
        self.lineAnswer.setGeometry(QtCore.QRect(40, 270, 711, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lineAnswer.setFont(font)
        self.lineAnswer.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineAnswer.setObjectName("lineAnswer")
        self.lblAnswer = QtWidgets.QLabel(self.centralwidget)
        self.lblAnswer.setEnabled(False)
        self.lblAnswer.setGeometry(QtCore.QRect(40, 220, 711, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblAnswer.setFont(font)
        self.lblAnswer.setText("")
        self.lblAnswer.setObjectName("lblAnswer")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(420, 10, 331, 111))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 41, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 73, 59, 16))
        self.label_3.setObjectName("label_3")
        self.lblTime = QtWidgets.QLabel(self.groupBox)
        self.lblTime.setGeometry(QtCore.QRect(110, 40, 191, 16))
        self.lblTime.setText("")
        self.lblTime.setObjectName("lblTime")
        self.lblAccuracy = QtWidgets.QLabel(self.groupBox)
        self.lblAccuracy.setGeometry(QtCore.QRect(110, 74, 191, 16))
        self.lblAccuracy.setText("")
        self.lblAccuracy.setObjectName("lblAccuracy")
        self.btnStart = QtWidgets.QPushButton(self.centralwidget)
        self.btnStart.setGeometry(QtCore.QRect(30, 27, 311, 101))
        self.btnStart.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnStart.setDefault(False)
        self.btnStart.setObjectName("btnStart")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 774, 22))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.actionQuestions = QtWidgets.QAction(MainWindow)
        self.actionQuestions.setObjectName("actionQuestions")
        self.actionAddQuestion = QtWidgets.QAction(MainWindow)
        self.actionAddQuestion.setObjectName("actionAddQuestion")
        self.menuSettings.addAction(self.actionQuestions)
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.lineAnswer.textChanged['QString'].connect(MainWindow.changeAnswer)
        self.lineAnswer.returnPressed.connect(MainWindow.endAnswer)
        self.btnStart.clicked.connect(MainWindow.start)
        self.actionQuestions.triggered.connect(MainWindow.openManQuestionDlg)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Remington"))
        self.groupBox.setTitle(_translate("MainWindow", "Result"))
        self.label_2.setText(_translate("MainWindow", "Time:"))
        self.label_3.setText(_translate("MainWindow", "Accuracy:"))
        self.btnStart.setText(_translate("MainWindow", "Select a topic"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionQuestions.setText(_translate("MainWindow", "Questions"))
        self.actionAddQuestion.setText(_translate("MainWindow", "Add"))

